# Predict the CO2 emission of a car based on the size of the engine

In [4]:
import pandas as pd

In [6]:
df =pd.read_csv('cars.csv.csv')

In [42]:
X = df[['Volume', 'Weight']]
X.head()

   Volume  Weight
0  1000.0   790.0
1  1200.0  1160.0
2  1000.0   929.0
3   900.0   865.0
4  1500.0  1140.0

In [33]:
X.tail()

    Volume  Weight
33  1600.0  1390.0
34  1600.0  1405.0
35  2500.0  1395.0
36     NaN     NaN
37     NaN     NaN

In [34]:
X = X.fillna(0)
X.tail()

    Volume  Weight
33  1600.0  1390.0
34  1600.0  1405.0
35  2500.0  1395.0
36     0.0     0.0
37     0.0     0.0

In [32]:
y = df.CO2
y.tail()

33    108.0
34    109.0
35    120.0
36      NaN
37      NaN
Name: CO2, dtype: float64

In [36]:
y= y.fillna(0)
y.tail()

33    108.0
34    109.0
35    120.0
36      0.0
37      0.0
Name: CO2, dtype: float64

In [37]:
from sklearn import linear_model

In [38]:
reg = linear_model.LinearRegression()

In [39]:
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#predict the CO2 emission of a car where the weight is 2300kg, and the volume is 1300cm3

In [40]:
predictedCO2 = reg.predict([[2300, 1300]])

In [41]:
print(predictedCO2)

[106.92636402]